agentAddress  udp:161

override .1.3.6.1.2.1.1.1.0 octet_str "Network Engineering SmartPDU"
override .1.3.6.1.2.1.1.2.0 object_id ".1.3.6.1.4.1.2000.1"
override .1.3.6.1.2.1.1.4.0 octet_str ""
override .1.3.6.1.2.1.1.5.0 octet_str "NET-POWER"
override .1.3.6.1.2.1.1.6.0 octet_str ""
override .1.3.6.1.2.1.1.7.0 integer "72"

rocommunity public
rwcommunity private default .1.3.6.1.4.1.2000.1

pass_persist .1.3.6.1.4.1.2000.1 /path/to/executable/nesnmpd_helper
